[package]
name = "hunk"
version = "0.0.1"
authors = ["Dan Neumann <danrodneu@gmail.com>"]

[dependencies]
futures = "0.1"
hyper = "0.11"
mime = "0.3"
futures-cpupool = "0.1"
mime_guess = "2.0.0-alpha.3"
flate2 = "1.0"
lazy_static = "1.0"
clap = "2.29"
colored = "1.6"