[package]
name = "hunk"
version = "0.0.1"
authors = ["Dan Neumann <danrodneu@gmail.com>"]

[dependencies]
clap = "2.29"
colored = "1.6"
flate2 = "1.0"
futures = "0.1"
futures-cpupool = "0.1"
hyper = "0.11"
lazy_static = "1.0"
mime = "0.3"
