[package]
name = "hunk"
version = "0.0.1"
authors = ["Dan Neumann <danrodneu@gmail.com>"]

[dependencies]
futures = "*"
hyper = "*"
tokio-core = "*"
tokio = "*"
futures-cpupool = "*"
lazy_static = "*"
flate2 = "*"
colored = "*"
maud = "*"
percent-encoding = "*"
unicase = "*"
url = "*"
leak = "*"
chrono = "*"
atty = "*"
# Config parsing
serde = "1.0"
serde_derive = "1.0"
toml = "*"
regex = "*"